### ISSUE TITLE
Periodic server crashes

### ISSUE THREAD

**Issue by MrBlackCreep** [Elecs-Mods/ElecCore#103]
My custom modpack server is crashing roughly every hour when players are online. ElecCore is the only mod that appears in the description of the crash. They only started 2-3 days ago although the server has been running for a week now.
[crash-2017-03-12_14.08.12-server.txt](https://github.com/Elecs-Mods/ElecCore/files/836577/crash-2017-03-12_14.08.12-server.txt)
[crash-2017-03-12_15.06.31-server.txt](https://github.com/Elecs-Mods/ElecCore/files/836579/crash-2017-03-12_15.06.31-server.txt)
[crash-2017-03-12_16.04.24-server.txt](https://github.com/Elecs-Mods/ElecCore/files/836578/crash-2017-03-12_16.04.24-server.txt)
[crash-2017-03-11_19.26.41-server.txt](https://github.com/Elecs-Mods/ElecCore/files/836582/crash-2017-03-11_19.26.41-server.txt)
[crash-2017-03-11_20.30.07-server.txt](https://github.com/Elecs-Mods/ElecCore/files/836581/crash-2017-03-11_20.30.07-server.txt)
[crash-2017-03-11_23.13.35-server.txt](https://github.com/Elecs-Mods/ElecCore/files/836580/crash-2017-03-11_23.13.35-server.txt)
If you need anything else, let me know.

**Comment by Elec332** [comment]
You are using an outdated version, please reopen if you can reproduce this with version 409 :)
