### ISSUE TITLE
elec332.abstraction.manager.AbstractionManager

### ISSUE THREAD

**Issue by victorbrndls** [Elecs-Mods/ElecCore#105]
I had troubles using the crafting table IV mod, so [you said](https://github.com/Elecs-Mods/CraftingTable-IV/issues/58) that it probably solve the problem, when I compile the last version I get this error

https://pastebin.com/w5nLddEG

**Comment by Elec332** [comment]
Thats because you didnt merge it with the abstraction layer.
The new version is on curse, awaiting approval, so you won't have to wait long :)
