### ISSUE TITLE
Window doesn't open

### ISSUE THREAD

**Issue by victorbrndls** [Elecs-Mods/ElecCore#106]
I'm using the latest Forge version and the latest ElecCore too. If I try to open the crafting table IV on singleplayer it works, but on multiplayer it get this error

> 
> java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.inventory.InventoryBasic.<init>(Lnet/minecraft/util/text/ITextComponent;I)V
> 	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
> 	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
> Caused by: java.lang.NoSuchMethodError: net.minecraft.inventory.InventoryBasic.<init>(Lnet/minecraft/util/text/ITextComponent;I)V
> 	at elec332.core.inventory.window.WindowContainer.<clinit>(WindowContainer.java:407) ~[WindowContainer.class:?]
> 	at elec332.core.proxies.CommonProxy.getServerGuiElement(CommonProxy.java:38) ~[CommonProxy.class:?]
> 	at elec332.core.proxies.CommonProxy.getServerGuiElement(CommonProxy.java:12) ~[CommonProxy.class:?]
> 	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:254) ~[NetworkRegistry.class:?]
> 	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:89) ~[FMLNetworkHandler.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2504) ~[aay.class:?]
> 	at elec332.core.inventory.window.WindowManager.openWindow(WindowManager.java:166) ~[WindowManager.class:?]
> 	at elec332.core.inventory.window.WindowManager.openWindow(WindowManager.java:146) ~[WindowManager.class:?]
> 	at elec332.core.tile.TileEntityBase.openWindow(TileEntityBase.java:41) ~[TileEntityBase.class:?]
> 	at elec332.craftingtableiv.tileentity.TileEntityCraftingTableIV.onBlockActivated(TileEntityCraftingTableIV.java:109) ~[TileEntityCraftingTableIV.class:?]
> 	at elec332.core.tile.BlockTileBase.onBlockActivatedC(BlockTileBase.java:82) ~[BlockTileBase.class:?]
> 	at elec332.abstraction.impl.MCAbstractedBlock.func_180639_a(MCAbstractedBlock.java:43) ~[MCAbstractedBlock.class:?]
> 	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:447) ~[lz.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:685) ~[mi.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
> 	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 5 more

**Comment by Elec332** [comment]
I need a full crash log and the versions of the mods you used, I cannot do anything without that.
