### ISSUE TITLE
Possible conflict with Thaumic Infusion

### ISSUE THREAD

**Issue by MisterShawn** [Elecs-Mods/ElecCore#11]
I reported to Thamic Infusion's author, but I thought I should also post here. I've been having intermittent crashes while digging gravel/sand: http://hastebin.com/raw/oyezavazot

**Comment by MisterShawn** [comment]
I disabled both Crafting Table IV and ElecCore and still got the crash so I'm going to go ahead and close this.

**Comment by Elec332** [comment]
Yep, not on my side indeed :)
