### ISSUE TITLE
1.12.1 crash on startup

### ISSUE THREAD

**Issue by davqvist** [Elecs-Mods/ElecCore#116]
ElecCore 1.8.429
MC 1.12.1
Forge 2446

I tried to load my pack in 1.12.1 as basically nothing has changed and got the following crash, it seems like an incompability with Forestry.

https://pastebin.com/HQ25dbx9

**Comment by Kris1432** [comment]
Can confirm its just updating to 1.12.1 that is causing this.

**Comment by bbgott** [comment]
I got the same error, but only with forestry in my pack.  I want forestry in my pack, so this issue is a show stopper for me as this is a required dependency for deep resonance.

Forge: 2452
MC: 1.12.1
ElecCore: 1.8.429
Forestry: 5.5.0.163

**Comment by Kris1432** [comment]
EDIT: LINK REMOVED

**Comment by Kris1432** [comment]
that build doesn't work on servers @Elec332 https://pastebin.com/Bjsnsaws

**Comment by Kris1432** [comment]
#117 this fixes this issue here.

**Comment by ExDomino** [comment]
We are still looking for an update of the JAR.

**Comment by Kris1432** [comment]
EDIT: LINK REMOVED

**Comment by BrainStone** [comment]
Mind to upload that fix to Curse?

**Comment by Elec332** [comment]
Fixes have been uploaded to CF

@Kris1432 Could you please pull your builds from dropbox? The fix is on CF now ;)
