### ISSUE TITLE
[1.12.1] Client Crash in conjuction with DeepResonance

### ISSUE THREAD

**Issue by Morpheus1101** [Elecs-Mods/ElecCore#118]
Crash Log @ https://puu.sh/xd1yf/cf500350da.txt

**Comment by ZephaniahNoah** [comment]
Having the same problem here.
[crash-log.txt](https://github.com/Elecs-Mods/ElecCore/files/1237054/crash-2017-08-20_05.06.37-client.txt)
If I take forestry out it works fine.

**Comment by ChiefLogan3010** [comment]
[crash-2017-08-20_19.56.49-client.txt](https://github.com/Elecs-Mods/ElecCore/files/1237285/crash-2017-08-20_19.56.49-client.txt)
also getting this crash

**Comment by Kris1432** [comment]
see #116 please check the other issues before duplicating another one.
