### ISSUE TITLE
FML reports Fatal Error with tesla-core-lib when eleccore loaded

### ISSUE THREAD

**Issue by Thiana** [Elecs-Mods/ElecCore#119]
Forge is reporting a fatal level error with tesla-core-lib, but only when ElecCore is present.

```
[22:09:41] [main/FATAL] [FML]: Detected an attempt by a mod FMLMod:teslacorelib_registries{1.0.7} to perform game activity during mod construction. This is a serious programming error.
```

Log without ElecCore: https://paste.ee/p/k38IH
Log with ElecCore: https://paste.ee/p/XlRmT (line 147)
Log with ElecCore only: https://paste.ee/p/HCFeP (line 139)

Tagging @faceofcat since this is some sort of interaction issue and they might end up with bug reports.

Is this safe to ignore? Thanks.

Versions:
* MC 1.12.1
* Forge 14.22.0.2467
* ForgeLin 1.5.1
* tesla-core-lib 1.12-1.0.7
* ElecCore 1.12-1.8.430

**Comment by faceofcat** [comment]
'teslacorelib_registries' doesn't even subscribe to the construction event... so no idea what that could be about.

**Comment by faceofcat** [comment]
the culprit is probably this line of code:
https://github.com/Elecs-Mods/ElecCore/blob/cb73ddb23f55fd9a3a34ba2af27f7a59081af3a2/src/main/java/elec332/core/main/ElecCore.java#L125

probable proof:
![image](https://user-images.githubusercontent.com/23014228/30001273-c29e889c-9091-11e7-8635-ab6527d6c4c7.png)

**Comment by Elec332** [comment]
Yea, Its supposed to run that code with ElecCore as the activeContainer, so ElecCore gets blamed correctly, but this is thrown when I attempt to get the ElecCore ModContainer :P
