### ISSUE TITLE
[1.12.2] Crash with Forestry

### ISSUE THREAD

**Issue by MasterEnderman** [Elecs-Mods/ElecCore#122]
Forge: 14.23.0.2522
ElecCore: 1.8.430
Forestry: 5.7.0.209
Crash-Report: https://pastebin.com/FH48LGyU

**Comment by Staegrin** [comment]
Downgrading Forestry to version 5.6.0.201 seems to be a good temporary workaround.

**Comment by MasterEnderman** [comment]
But the 5.6.0.201 doesn't have the new module config system. Guess I have to turn ElecCore off for now.

**Comment by carstorm** [comment]
If it helps at all, I'm having the same issue https://pastebin.com/aajxC95R

For now, I downgraded forestry though I hope the issue is resolved soon.

**Comment by Tencao** [comment]
I've fixed this in a PR, #123 . Just need to wait for it to be pulled or for them to fix it themselves.

**Comment by madhatr** [comment]
When's that pull request going to get in?  Disabling ElecCore and DR for now.

**Comment by Tencao** [comment]
@madhatr The pull request was recently merged, so hopefully not long before it's released on curse

**Comment by Elec332** [comment]
Uploaded
