### ISSUE TITLE
Crash with the new version of forge

### ISSUE THREAD

**Issue by ghost** [Elecs-Mods/ElecCore#125]
https://gist.github.com/xKnightGamingx/8fcdae26f968cf420e7ac3272e296cb2

**Comment by SnowShock35** [comment]
Crash is with newer Forestry not Forge. The likelihood a bug is broken because of Forge is highly unlikely especially when there's already like 100 other mods loaded. 😉

Therefore, duplicate of #122

**Comment by SethWilliamson** [comment]
Runs fine with Forge 14.23.0.2537, MC 1.12.2

**Comment by Elec332** [comment]
Fixed, and yes, this was an incompatibility with the latest Forestry versions.
