### ISSUE TITLE
Odd Dimension interaction crash.

### ISSUE THREAD

**Issue by border999** [Elecs-Mods/ElecCore#127]
https://pastebin.com/Ze6WdTER
???

**Comment by border999** [comment]
I'll also say that I suspect that your core might be having issues with the 1.12.2 version of buildcraft.

**Comment by Isolonice** [comment]
Getting the same crash: https://pastebin.com/dNFGtA2E

**Comment by Unbr34k4bl3** [comment]
Same here. Was playing with the direwolf20 pack and had MAJOR issues while holding ender lillies.
https://pastebin.com/XtfyUkt4

**Comment by border999** [comment]
Same here for the ender Lillies. But that issue is not related to this one as lagging while holding an ender lily was an issue before Buildcraft came out with a 1.12.2 version. Trust me, I KNOW!

**Comment by Unbr34k4bl3** [comment]
Interesting. Because the crash of which I pastebined uptop happened upon holding a stack of exactly 33 ender lillys in my hand. Extreme lag > crash after 5 minutes of freeze and no interaction. ...

Well this is my experience anyways. Also I don't play with buildcraft. So I don't think it conflicts with that...

**Comment by border999** [comment]
It was a throw away mention. But I will say per the actual issue for which this discussion is about, that while the "latest" versions of forge and Extra Utilities 2 solve the problem of being unable to enter the world. The crash still occurs every so often and I have yet to identify if It's something I'm doing or if it's something under the hood catching on something else and crashing.

**Comment by Elec332** [comment]
This is extremely weird, Ill be able to investigate this further next weekend

**Comment by Unbr34k4bl3** [comment]
Small update: I updated to the latest of all mods, seems to be fixed for now? Will update thread if I find anything new.

**Comment by belathus** [comment]
I just started getting this crash. I have enderlilies disabled and we don't have Buildcraft installed.

Restoring the world to a backup from before the crash started happening doesn't seem to help, either.

https://gist.github.com/belathus/0a2e473a05dc5db91ff9d30cac6a372c

**Comment by ghost** [comment]
Setting "B:GlassCables=false" from ae2 mod fixed it

Edit: Unloading each chunk before unloading the world doesn't crash.

**Comment by Dankman** [comment]
I had it as well.

https://pastebin.com/KAXjkFGc

**Comment by Dankman** [comment]
Server has yet to crash after I wiped my rftools dimensions, well, dimensions.

**Comment by border999** [comment]
seems like various issues are popping up here.
