### ISSUE TITLE
[ElecCore 1.12.2-1.8.443, Forge 14.23.1.2566] Unable to load singleplayer world

### ISSUE THREAD

**Issue by dsmall3303** [Elecs-Mods/ElecCore#131]
For some reason, I found myself unable to load my world. I've been able to do so before, but when I try to now, the game just hangs, and upon closing Minecraft, I found a crash report. I tried again to verify, so see both attached crash reports:
[crash-2018-01-19_19.45.38-server.txt](https://github.com/Elecs-Mods/ElecCore/files/1648476/crash-2018-01-19_19.45.38-server.txt)
[crash-2018-01-19_19.59.33-server.txt](https://github.com/Elecs-Mods/ElecCore/files/1648477/crash-2018-01-19_19.59.33-server.txt)

**Comment by Elec332** [comment]
You are using an outdated version, please update.
