### ISSUE TITLE
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by ProsperCraft** [Elecs-Mods/ElecCore#133]
https://gist.github.com/ProsperCraft/93cb325cff7e14f57f4a6ab96cb6d262

This was in console.
Logs attached.
[ProsperCraftLogs.zip](https://github.com/Elecs-Mods/ElecCore/files/1652368/ProsperCraftLogs.zip)

**Comment by ktole1999** [comment]
hello, has this been pushed to curse? latest on curse is 12/17/2017  1.8.434
