### ISSUE TITLE
Crash during pre-init

### ISSUE THREAD

**Issue by modmuss50** [Elecs-Mods/ElecCore#136]
https://gist.github.com/modmuss50/e84a837e0b560594b024c1a0f6cef96e

All mods are the latest on curse, let me know if you need more info.

 My guess is its due to another mod doing something stupid (Or me being stupid by installing 700 mods).

**Comment by Elec332** [comment]
Hmmm, looks interesting.
This shouldn't be able to happen, but Ill look into it :)

**Comment by luke-bravenboer** [comment]
I also experienced the same exception- I can confirm that this is caused by an incompatibility with Vazkii's **Player's Choice** (v1.1-3).

Here's the issue I raised with his side, though it's unclear where the root cause is as of yet: https://github.com/Vazkii/PlayersChoice/issues/2

**Comment by Elec332** [comment]
I think I know what's going on

**Comment by luke-bravenboer** [comment]
Would it be feasible to simply return early if the asmData is null during the ModuleManager's preInitLast method? Since it only affects the initial fake-load cycle caused by player's choice, it shouldn't matter if things are being loaded correctly at this point
