### ISSUE TITLE
Crash on startup - ElecCore-1.8.9-1.4.220

### ISSUE THREAD

**Issue by The-Fireplace** [Elecs-Mods/ElecCore#14]
http://paste.ubuntu.com/14655519/

**Comment by Elec332** [comment]
Can you reproduce this with forge 1715 or higher?

**Comment by The-Fireplace** [comment]
One minute and I'll test it. If I can't, then you will need to set the minimum required Forge version.

**Comment by Elec332** [comment]
Indeed

**Comment by The-Fireplace** [comment]
Yes, it works on the latest forge version.
