### ISSUE TITLE
Issues closed??

### ISSUE THREAD

**Issue by mindcloud69** [Elecs-Mods/ElecCore#140]
I hate to be the person who asks but there are several issues that you have closed that are causing problems on my server, however we have not gotten an update since 2017. I need to know if there is going to be a bugfix release soon so I can decide if I will be keeping your mods installed for my community.

**Comment by P3rf3ctXZer0** [comment]
I recommend avoiding mods that just close issues without solutions.

**Comment by Elec332** [comment]
> I recommend avoiding mods that just close issues without solutions.

I thought I'd fixed the issue, but there were a lot of duplicate issues, so I didn't react to every single one.

Anyways, the mod has been rewritten (which fixes all currently known issues), you can download it here:
https://minecraft.curseforge.com/projects/eleccore/files/2678966

**Comment by P3rf3ctXZer0** [comment]
Nice.
