### ISSUE TITLE
Minecraft won't finish loading textures with eleccore mod installed

### ISSUE THREAD

**Issue by connerfick** [Elecs-Mods/ElecCore#145]
I am not exactly sure what happened, but I have the crash report and mod list.

Minecraft: 1.9.0
Forge: 12.16.1.1934

[crash-2019-09-14_09.17.21-client.txt](https://github.com/Elecs-Mods/ElecCore/files/3612790/crash-2019-09-14_09.17.21-client.txt)
![Mod List](https://user-images.githubusercontent.com/8696913/64909514-d5cd7980-d6d2-11e9-8aaf-d787ba3c5de2.jpg)

**Comment by Elec332** [comment]
Please try with the latest version for 1.9.4:
https://www.curseforge.com/minecraft/mc-mods/eleccore/files/2325968

Edit: Whoops, wrong MC version

**Comment by Elec332** [comment]
This issue was fixed with the first 1.9.4 release
