### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by blairwilson** [Elecs-Mods/ElecCore#146]
https://gist.github.com/HHServers/f2c92783f28960aafb06c13c38d5ac52

ATM3 Remix V1.5.2
ElecCore-1.12.2-1.9.452

Let me know if more info is needed

**Comment by Elec332** [comment]
I see you are using Sponge.
Sponge is unfortunately not always manipulating forge events properly
Changing "supressSpongeIssues" to true in the eleccore config file should resolve this.

Please re-open if the issue persists.
