### ISSUE TITLE
Error if Hwyla is missing

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/ElecCore#147]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25 Beta`
 
I get the following error on game launch if Hwyla (Waila) is not installed.
![2020-01-06_14 19 16](https://user-images.githubusercontent.com/12000593/71846710-d8dce300-3090-11ea-89aa-7b12a0beae9a.png)

**Comment by Elec332** [comment]
https://github.com/Elecs-Mods/ElecCore/commit/a53531720cf66dc5dd6a523013ee3f84aa481575
