### ISSUE TITLE
Crash with banner rendering

### ISSUE THREAD

**Issue by WenXin20** [Elecs-Mods/ElecCore#148]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25 Beta`

I got this crash while scrolling through the creative menu. The game crashed trying to render banners. Only ElecCore & Hwyla is installed.
[Crash Report](https://gist.github.com/WenXin20/895f3723a99a683e19523e8070235c9e)

**Comment by Elec332** [comment]
And this doesn't happen with only Hwyla installed?

**Comment by WenXin20** [comment]
I'm pretty sure it doesn't since I've been using that mod for a while now, but I'll test it to be sure.

**Comment by WenXin20** [comment]
Interesting...
I can't reproduce the crash...

**Comment by Elec332** [comment]
I think this is a vanilla/forge bug then, as I do not see anything referencing ElecCore.
Neither do I have ASM transformers or AT's modifying banners.

If you keep getting this and can trace it to any of my mods, please feel free to open an issue for it.

**Comment by WenXin20** [comment]
Thanks, I'm guessing it was one of those super rare crashes.

**Comment by Elec332** [comment]
Probably, but please do not hesitate to open a new issue if it happens again and it looks to be ElecCore's fault.

**Comment by WenXin20** [comment]
Thanks, will do!
