### ISSUE TITLE
ElecCoreLoader (eleccoreloader) encountered an error processing deferred work...

### ISSUE THREAD

**Issue by Gamerbolts** [Elecs-Mods/ElecCore#149]
Hey there! I am creating a modpack for my friends and I and I got everything running clientside, I went to go test serverside and came across this:

https://pastebin.com/CHwy0kQB

Not sure really what it means but I was thinking ElecCore is calling to something clientside? I am not a programmer so could be wrong but wanted to bring it up to you and see if this issue could be fixed. Thanks!

**Comment by tlitookilakin** [comment]
Had the same problem
