### ISSUE TITLE
Problem with hand rendering

### ISSUE THREAD

**Issue by ghost** [Elecs-Mods/ElecCore#15]
holding no item http://i.imgur.com/PU8Lk50.png

Punching: http://i.imgur.com/wq5pw6X.png

**Comment by Elec332** [comment]
Closing as I cannot even reproduce this with the latest version of FTB unstable: http://prntscr.com/9xd7rk

**Comment by BBoldt** [comment]
@Elec332 Try my pack, easily reproducible, also unlike Unstable, I ship your mod. http://minecraft.curseforge.com/projects/the-pioneers?gameCategorySlug=modpacks&projectID=241377

**Comment by BBoldt** [comment]
https://github.com/BBoldt/ThePioneers/issues/8
