### ISSUE TITLE
Odd Mod interaction

### ISSUE THREAD

**Issue by LabGoblin** [Elecs-Mods/ElecCore#18]
if you have ElecCore and Redstone Paste installed Redstone Paste fails to render.
im in the process of contacting FyberOptic also
https://www.dropbox.com/sh/z7kw3k0ozyu3bzm/AACEPzGVi3gijp31_1rkar8ma?dl=0

**Comment by LabGoblin** [comment]
i have contacted FyberOptic on [MCF](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291890-redstone-paste-mod?page=18) and on twitter

**Comment by MrGraphic** [comment]
Ahhh, was wondering what happened with my redstone paste. No I know.

**Comment by LabGoblin** [comment]
fortunately it seems to only impack rendering
