### ISSUE TITLE
[Issue?] NBT Issue

### ISSUE THREAD

**Issue by accessdenied0** [Elecs-Mods/ElecCore#2]
Hi dear @Elec332,

I recently got this issue with my SSP-world: http://pastebin.com/6SN77E3b after I updated ExtraUtilities today (1.2.10 to 1.2.11) but after this I can not play on my world anymore. It loads up I can see the world and 2 seconds after this it crashes. I downgraded ExtraUtilities but It doesn't changed...

I guess, according to this crash, It is something messed up with my ntbs is there a possible fix?
I'm sorry if this isn't even a fault on your side.

I hope you can help,

access_denied

**Comment by Elec332** [comment]
This has been fixed by the latest ElecCore version (uploaded 2 days ago :P)
Try that version, if it still crashes then, go to the save folder of the crashing world,
find the folder called "elec332" and delete it (and all its contents)
