### ISSUE TITLE
Crash.... Help?  1.8.9

### ISSUE THREAD

**Issue by EndermanParty** [Elecs-Mods/ElecCore#20]
I was mining in my world when I came to a mineshaft, something in the mineshaft (Maybe an ore?) crashes me everytime I load the world. It said something to do with your mod, so I am posting it here.
http://paste.ee/p/owNHO

**Comment by EndermanParty** [comment]
I have EFlux as well, but ElecCore is being blamed for everything.

**Comment by Elec332** [comment]
Yes, this has been fixed

**Comment by EndermanParty** [comment]
Thank you, I just saw this on curseforge
