### ISSUE TITLE
eleccore-1.9-1.4.257 crashes dedicated forge server 1.9 build 1809-1811 on startup, now with crash report.

### ISSUE THREAD

**Issue by kreezxil** [Elecs-Mods/ElecCore#25]
Issue: {eleccore-1.9-1.4.257 crashes dedicated forge server 1.9 build 1809 on startup, there is no crash-report}

https://gist.github.com/9cc5abf8cc5012f9e160

**Comment by kreezxil** [comment]
I upgraded forge to 1811, now I have a crash report

Issue: eleccore-1.9-1.4.257 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/155cb8a5236ff6cacc3c

fml server latest:
https://gist.github.com/bfbcb167905c0e6eb0f0

**Comment by AxolotlAccount** [comment]
similar type of crash happened to me:

http://pastebin.com/NrAjq2vR

**Comment by Lanse505** [comment]
Yup can also confirm this crash
http://puu.sh/nV2vR/42e15f4083.txt

**Comment by ashly138** [comment]
http://paste.ee/p/W9xc3

**Comment by canitzp** [comment]
This crash is because Forge updated some important stuff

**Comment by kreezxil** [comment]
I'm posting this here because it is essentially the same crash but also on build 1811 and this time there is a crash report! Yay!

Issue: eleccore-1.9-1.4.257 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/5d7f0769c7c4ba4e7a1c

fml server latest:
https://gist.github.com/2e8687dfa3022dfc6dc9

**Comment by Elec332** [comment]
Fixed in the latest release, should be on CF any minute
