### ISSUE TITLE
wierd starting up crash with elecore and bc trans pipes 

### ISSUE THREAD

**Issue by SDUBZ** [Elecs-Mods/ElecCore#27]
here i dont know what to make of it http://pastebin.com/icxF1A9N

**Comment by canitzp** [comment]
BC is crashed, please  post it to the buildcraft repo.

**Comment by SDUBZ** [comment]
already did thought id post it here too since your mod was mentioned just being safe :D

**Comment by Elec332** [comment]
Yep, not me ;)
