### ISSUE TITLE
Version 1.8.9-1.4.247 Throws Error due to a Mod Rejection

### ISSUE THREAD

**Issue by MastaC729** [Elecs-Mods/ElecCore#28]
My client was missing a mod, and the following two errors were spammed in the server's console:

http://pastebin.com/gAd1nNkS

Thought I'd let you know this is happening; it doesn't cause the server or client to crash, but it spams the console a bit.

**Comment by Elec332** [comment]
It's not the mod reject, it's that the client disconnects before actually being connected

**Comment by MastaC729** [comment]
Ah derp, I was focused on some other mods at the time that were throwing stacktraces, which made me just automatically assume this was an error due to ElecCore.
