### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by blockbreaker1361** [Elecs-Mods/ElecCore#29]
Just got this crash with the latest version of the mod
http://pastebin.com/vL7ZpqYV

**Comment by livehass** [comment]
hey man, 
I had this same problem but, a fix that simple, you need to downgrade to ElecCore-1.8.9-1.4.240 this version if keep crashing, seach in the mod folders to E-flux mod I removed E-flux and work perfectly, good luck and good plays to you.

**Comment by Elec332** [comment]
Will be fixed, but this is not an ELecCore issue. I just need to recompile DR & EFlux
