### ISSUE TITLE
java EOF Crash

### ISSUE THREAD

**Issue by Happy4077** [Elecs-Mods/ElecCore#3]
So I am getting this weird crash with my world. I was able to run it yesterday, and now upon reloading it today have gotten this crash twice. 
Any thoughts?
http://pastebin.com/U4s5sewS

**Comment by Happy4077** [comment]
Here are the last two events in the log before the crash (Not included in the pastebin)
[17:17:22] [Server thread/ERROR] [FML]: 68: ASM: resonant.lib.utility.nbt.SaveManager@452ab508 worldSave(Lnet/minecraftforge/event/world/WorldEvent;)V
[17:17:22] [Server thread/ERROR]: Encountered an unexpected exception

**Comment by Elec332** [comment]
Did this happen after a crash or a forced shutdown?

**Comment by Happy4077** [comment]
So what would happen is that if I had a world crash for any reason, I would never be able to replay it. Also, I would get this crash (Very rarely) after simply logging out of a world with no crash. So I guess my answer to your question is yes.
