### ISSUE TITLE
Crash with AbstractExplosion

### ISSUE THREAD

**Issue by DemoXinMC** [Elecs-Mods/ElecCore#30]
It would appear that AbstractExplosion is loading null entities into the list, which other mods are not expecting to have to handle.  Vanilla explosions do not place null entities in it's in-range list.

http://pastebin.com/x90Bzf82

**Comment by canitzp** [comment]
Please report it to Pneumaticcraft too, cause it crashed MC

**Comment by Elec332** [comment]
Nah, this is on my end, as I pass a null List<Entity>.

**Comment by Elec332** [comment]
Fixed by: https://github.com/Elecs-Mods/ElecCore/commit/9645c70bd80566a681bd48961a3224a3c47b56ac

(Forgot to close it in the commit itself -_-)

**Comment by DemoXinMC** [comment]
Any chance you could give us a timeline for when this will be corrected on Curse?  I'm using the 1.8.9 version for a streamer's sub server pack and we discovered this issue during testing.

**Comment by Elec332** [comment]
oh, 1.8.9.....

Probably monday

**Comment by DemoXinMC** [comment]
So, any update on when we're going to get this fix in a Curse release?
