### ISSUE TITLE
Client Crash (1.8.9)

### ISSUE THREAD

**Issue by drewbit** [Elecs-Mods/ElecCore#31]
I have enderio redstone conduit pointing into redstone clocks from ExtraUtilities2. The stacktrace points towards ElecCore, so I figured I'd open an issue here. (I have already put one up on EnderIO's github.)

Here's the log: http://paste.ee/p/kvmm1

**Comment by Xiaminou** [comment]
SleepyTrousers/EnderIO#3272

and an unrelated quesiton: I see you are using Immersive Engineering, may I ask, where did you get it? I can't find the 1.8.9 version anywhere.

**Comment by drewbit** [comment]
There are pre-releases available if you subscribe to BluSunrize's patreon. 
https://www.patreon.com/BluSunrize

**Comment by Elec332** [comment]
This is not on my end.
