### ISSUE TITLE
Explosion Crash

### ISSUE THREAD

**Issue by CandiceJoy** [Elecs-Mods/ElecCore#32]
http://pastebin.com/fx5tFxwN

It looks like AbstractExplosion is calling a polymorphic form of the super constructor that doesn't exist.

I have 2 current theories.

The line in question is:
super(world, entity, x, y, z, size, Lists.<BlockPos>newArrayList());

My first theory is that Explosion's constructor has parameters (World, Entity, double, double, double, float, List<BlockPos>) and I don't think your syntax there actually converts the List to a List<BlockPos>, thus the error that Explosion(World, Entity, double, double, double, float List) doesn't exist because, well, it doesn't.  However, that doesn't explain why it compiled in the first place, which is odd.

My second theory is that that constructor is client-side only and the error was thrown on the server, indicating that the client-side method is being called on the server-side, thus leading to the problem.

**Comment by Elec332** [comment]
Shite: 

![](http://i.imgur.com/3hSW3i1.png)

**Comment by CandiceJoy** [comment]
Ahh, so second theory it is xP

**Comment by Elec332** [comment]
Fixed in latest commit

**Comment by CandiceJoy** [comment]
Cool.  Any idea when we can expect a 1.8.9 build on Curse with the fix?  I'm working on a pack for tlovetech and this is the major hurdle we're running into right now.

Thanks!
<3Candi

**Comment by Elec332** [comment]
Oh, 1.8.9, eh, let me fix that for that version too then ;)
