### ISSUE TITLE
ElecCore-1.9-1.4.270 Causing a crash where 266 does not

### ISSUE THREAD

**Issue by ghost** [Elecs-Mods/ElecCore#34]
The instance just crash when trying to load.

Here is the log:
http://pastebin.com/tHmDYRFK

**Comment by Elec332** [comment]
Seems like I accidentally made ElecCore depend on MCMultiPart. This will be fixed if you install it.

**Comment by MokahTGS** [comment]
Confirming this crash: http://pastebin.com/HzVQ9hZc
