### ISSUE TITLE
NoClassDefFoundError on Dedicated Server

### ISSUE THREAD

**Issue by Ommina** [Elecs-Mods/ElecCore#4]
Single player loads up fine, but server crashes with:

http://pastebin.com/MuTVqyGx

Not much else to offer other than that.  Paste contains complete mod list.  This is an existing world, but it isn't get anywhere near loading the world so I don't (think!) existing goodies are a factor.

ElecCore-1.7.10-1.4.152.jar

**Comment by Elec332** [comment]
What? How? Ill put this on hight priority.
