### ISSUE TITLE
[1.9.4] Crash on startup

### ISSUE THREAD

**Issue by KristjanKr** [Elecs-Mods/ElecCore#42]
http://paste.ee/p/zqqkn Here is the crash log, crashes when starting game.

**Comment by AxolotlAccount** [comment]
not same, but it crashes in modeling too.

my crash report(java heap space): 

https://gist.github.com/EnderT5/640ed53e8f0ea171d54e6e5adf8faba1

**Comment by Elec332** [comment]
@EnderT5 Allocate more RAM, crash is also not related to ElecCore
@KristjanKr Has already been fixed, fix will be uploaded today

**Comment by AxolotlAccount** [comment]
ummmm, 179 modded ftb infinity evolved, 70+ fps in game

116 modded 1.9.4 testing pack java heap space crash on startup

please help :/

**Comment by Elec332** [comment]
This is probably because there is an completely new rendering system in 1.8+

You are goint to have to allocate more RAM or remove some of the mods.
NOTE: As I stated before, the crash has nothing to do with ElecCore
