### ISSUE TITLE
(1.9) Crash on loading Minecraft

### ISSUE THREAD

**Issue by HendrikJ79** [Elecs-Mods/ElecCore#43]
During startup of the game the game crashes with the following crash-log:
https://gist.github.com/HendrikJ79/5a2450d315ae2b31068a5f18fbb1f944

**Comment by Elec332** [comment]
You are using a very (old) version, please update.
(Its been fixed in a later version)

**Comment by HendrikJ79** [comment]
I can't update it because I have ElecCore-1.9-1.4.270.jar and can't finf any newer version.
I am using Curse.

**Comment by Elec332** [comment]
http://mods.curse.com/mc-mods/minecraft/227391-eleccore-rendering-library#t1:other-downloads
Latest is ElecCore-1.9.4-1.5.292
