### ISSUE TITLE
Crash corrupted world

### ISSUE THREAD

**Issue by Chromogen** [Elecs-Mods/ElecCore#46]
Hey there, i really cant reproduce in details but i played 1.10 unstable and ran into a minecraft->windows crash
must be something with deepresonance or RFtools. only appeared when i started with them
unfortunately no log or any kind of crashreport available.

after trying to reload the world i ran into this one

http://pastebin.com/uqVYg40P

**Comment by exaskye** [comment]
Sorry, that commit doesn't actually fix this issue, I misread the issue list. GitHub has no way to remove the commit.
