### ISSUE TITLE
Tick!

### ISSUE THREAD

**Issue by 4rz0** [Elecs-Mods/ElecCore#5]
Is this line supposed to be in there?
https://github.com/Elecs-Mods/ElecCore/blob/20e9621bd33b9cf6a9533fba80d52b81c2fc3a4f/src/main/java/elec332/core/grid/basic/AbstractWorldGridHolder.java#L172
Having a log-entry each tick doesn't sound like a good idea ;D

**Comment by Elec332** [comment]
It only does so if ElecCore is set to debug mode: 
https://github.com/Elecs-Mods/ElecCore/blob/master/src/main/java/elec332/core/main/ElecCore.java#L93

**Comment by smbarbour** [comment]
Good to know.  Also, I'm not sure how, but the debug value was set to true when the config generated.

**Comment by Elec332** [comment]
Weird
