### ISSUE TITLE
ElecCore Crash

### ISSUE THREAD

**Issue by DatrixTHLK** [Elecs-Mods/ElecCore#51]
This is what the Output is saying for the Crash Log 
crash log: http://pastebin.com/ixUH2Fdn
FML Log: https://www.pastefs.com/pid/3771 (Sorry pastebin isn't happy when I have more than 500kb of data to post)
ElecCore: 1.5.303
Minecraft: 1.10.2
Forge: 12.18.1.2046-12.18.1.2048
A previous version of Forge (2043) used was able to work with this mod, after that doesn't cooperate.

**Comment by Elec332** [comment]
I do not see how this is related to ElecCore
Im sorry, but it probably ain't me.

**Comment by DatrixTHLK** [comment]
Ok...thanks.
