### ISSUE TITLE
1.5.303 crashes dedicated Forge server 1.10.2 build 2068 during gameplay

### ISSUE THREAD

**Issue by kreezxil** [Elecs-Mods/ElecCore#53]
I'm not sure what any of us were doing to cause the crash. :(

crash report:
https://gist.github.com/69f6f710598e607fcd5ed4524657b5a3

fml server latest:
https://gist.github.com/f3791f7df128948cf730ba4f2e163802

**Comment by DietmarKrause** [comment]
perhaps same thing here: https://github.com/SleepyTrousers/EnderIO/issues/3626
and here: https://github.com/whatthedrunk/allthemods/issues/95 
both have similar crash logs and happen while leaving the nether to the overwold. First link dig deep in it and he thinks elec core seems to be the problem.

**Comment by ShaCraft** [comment]
I can create the crash with either RFtools or Ender IO. even faster if both are installed. remove both and Elec core the crash stops. Sorry for not posting here sooner been busy at work. The one thing I still need to test is if I can get the crash on all Level-gens. I have been using the Quark gen and never though till now to test that. 

I'll test that when I get off work tomorrow.
RG_Sha
