### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 (Crash loading server)

### ISSUE THREAD

**Issue by Gamerbolts** [Elecs-Mods/ElecCore#54]
Hi, I am getting a crash on my server upon loading it up. 

http://pastebin.com/te2yyKXY Here is the crash log

Not too sure what is going on. Any help is appreciated. Thanks!

**Comment by Elec332** [comment]
Does it still crash when you try to start it again?

**Comment by Gamerbolts** [comment]
I started it again and it worked. Haven't received the crash since

**Comment by Elec332** [comment]
Good, thats what I expected :)

Im closing this for now, please reopen if it happens again.
