### ISSUE TITLE
Crash during stop

### ISSUE THREAD

**Issue by utoc** [Elecs-Mods/ElecCore#56]
See crash here: http://pastebin.com/RsWhrnet

Running eleccore 1.6.326 (just released) with FML2095.  

Let me know if you need full FML log file.

EDIT: Nevermind, we are getting corruption in loaded chunks while its trying to save

**Comment by Xiaminou** [comment]
I think I have the same problem: https://github.com/McJty/RFToolsDimensions/issues/43#issuecomment-253200844
or is it a different one?
