### ISSUE TITLE
[1.10.2-1.6.326] ConcurrentModificationException and server crash

### ISSUE THREAD

**Issue by RealGrep** [Elecs-Mods/ElecCore#57]
I've been having regular ticking world crashes lately, which may or may not be related, but they involve ConcurrentModificationExceptions, ticking world, and a prompt server crash. However, I just got this one, which provides more useful information to help figure it out.

The log is normal and fine until this happens, and the server crashes: http://hastebin.com/oyibudugig.md

MC 1.10.2, ElecCore 1.6.326, Forge 2095. Of course, let me know if you need anything else. Thanks!

EDIT: In trying to figure out the source of the other ticking world crashes and isolating them, and since I've eliminated most other possible causes, I've temporarily removed ElecCore and Deep Resonance. But it will take a while without crashes to know if that was it. If they stop as a result, I will post it here.

EDIT: Nope, those crashes still happen, so they are not likely related to this one.

**Comment by Elec332** [comment]
Modlist?
Do you have some kind of multithreading mod?

**Comment by RealGrep** [comment]
No multithreading mod, to my knowledge. And I did piece the pack together mod by mod, and none say they do so, anyway.

As for mod list, hopefully this list from which I build my manifest file will do. If not, I can go back and find the actual full log that contains a list in it. https://www.dropbox.com/s/b8nc869qwrjzkh9/ModList%20%28Case%20Conflict%29.txt?dl=0

The format (in CSV) is mod name, Curse mod ID, Curse file ID.

**Comment by Elec332** [comment]
New version will be uploaded to CF, please open a new ticket if the issue persists in that version
