### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by CubeTwo** [Elecs-Mods/ElecCore#58]
After i go away from my base server crash, if i stay in my base all works good.
crash report:
http://pastebin.com/19JjYHZy

**Comment by SharkWipf** [comment]
Getting the same issue on the latest versions of ElecCore and Deep Resonance currently available, as soon as the chunks my base (and, by extent, my Deep Resonance machines) is in are unloaded, the server crashes.

Crash report: [Pastebin](http://pastebin.com/5uD8DSbc)
