### ISSUE TITLE
Latest version crashes on world load

### ISSUE THREAD

**Issue by SharkWipf** [Elecs-Mods/ElecCore#62]
Latest version of ElecCore currently available on Curse (ElecCore-1.10.2-1.6.327.jar) causes a crash as soon as a (new or existing) world is loaded.
Happens both serverside and clientside.

Crash log: [pastebin](http://pastebin.com/eKRYvwJw)

**Comment by SharkWipf** [comment]
Oops nevermind, just read the closed issues and seeing it'll be fixed in the next release

**Comment by Elec332** [comment]
Its indeed been fixed in 1.6.327
