### ISSUE TITLE
Crash on world load (SP)

### ISSUE THREAD

**Issue by 3x1at1on** [Elecs-Mods/ElecCore#63]
Server crash on world load (SP) using latest ElecCore
Crash report: http://pastebin.com/N5hp8Qxn
FML log [fml-client-latest.txt](https://github.com/Elecs-Mods/ElecCore/files/531265/fml-client-latest.txt)

Unless this was fixed with https://github.com/Elecs-Mods/ElecCore/commit/86d5d3d29f953e20f4012b559bf26481089c5dce and I am just impatient!

Many thanks.

**Comment by xlxAciDxlx** [comment]
This has already been reported and fixed, Curse hasn't synced the latest version for some reason.
