### ISSUE TITLE
Crashing with ElecCore-1.10.2-1.6.328

### ISSUE THREAD

**Issue by StoneLegion** [Elecs-Mods/ElecCore#64]
I tried updating ElecCore-1.10.2-1.6.328.jar from ElecCore-1.10.2-1.6.326.jar and I started to stall when I was loading the world. I checked the logs and got the following:

http://pastebin.com/uAakFxwJ

Hope this helps using forge version:
2106.

**Comment by Elec332** [comment]
Pretty sure you are using version 1.6.327, this has been fixed in 1.6.328

**Comment by Elec332** [comment]
If you keep getting this crash, please post the entire crashlog and reopen this issue
