### ISSUE TITLE
Null pointer exception/ server crash

### ISSUE THREAD

**Issue by UberAffe** [Elecs-Mods/ElecCore#66]
[crash-2016-10-28_03.37.28-server.txt](https://github.com/Elecs-Mods/ElecCore/files/556862/crash-2016-10-28_03.37.28-server.txt)

Currently asking around the players to see what in-game thing might have cause it.

Edit:
Supposedly no one was doing anything directly with deep resonance which I believe is the only mod in HermitPack 1.1.0 that uses ElecCore.

**Comment by ProsperCraft** [comment]
Whenever you post a crash report, its best to check to see if there is an identical crash report already filed, there was only one issue, and its identical ;)

https://github.com/Elecs-Mods/ElecCore/issues/65

**Comment by ProsperCraft** [comment]
Thank you for posting though, this proves its not sponge :)

**Comment by UberAffe** [comment]
Yours is a state exception though, they are probably related but an NPE likely just means they didn't check for null somewhere. An IllegalStatException might be from ElecCore expecting the api to do things it's not.

**Comment by Elec332** [comment]
This is completely unrelated to #65 This has been fixed withing 8 hours after the release of the version in this pack, so the fix is already on CF, just not in the pack.

Im sorry, but there is nothing I can do about it.
