### ISSUE TITLE
ElecTileEntityItemStackRenderer not chaining

### ISSUE THREAD

**Issue by HellFirePvP** [Elecs-Mods/ElecCore#67]
Your TEISR, namely ElecTileEntityItemStackRenderer, isn't chaining. please consider that other people are also using the TileEntityItemStackRenderer to do special rendering. calling super.renderByItem isn't enough. Please consider keeping the old TEISR and call its renderByItem instead of the super one.

Example can be found in mine:

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/client/util/item/AstralTEISR.java

instantiate it with the "old" one that was previously in the TEISR.instance field and chain it that way.

Thanks in advance.

**Comment by Saereth** [comment]
Can confirm this is breaking the rendering on a few other mods as well, slashblade for sure.

**Comment by Elec332** [comment]
Fixed in latest release
