### ISSUE TITLE
server error when player joins

### ISSUE THREAD

**Issue by thegameoil** [Elecs-Mods/ElecCore#70]
Server thread/INFO thegameoil left the game
24.11 12:08:39 [Server] Server thread/ERROR [ElecCore]: Finished investigation.
24.11 12:08:39 [Server] Server thread/ERROR [ElecCore]: No additional errors found...
24.11 12:08:39 [Server] Server thread/ERROR [ElecCore]: Starting thorough investigation...
24.11 12:08:39 [Server] Server thread/ERROR [ElecCore]: Player: TextComponent{text='', siblings=[TextComponent{text='thegameoil', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg thegameoil '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:"thegameoil",id:"395c9aaf-5ec3-4ded-89e2-f6898fcb8013"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=thegameoil}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg thegameoil '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:"thegameoil",id:"395c9aaf-5ec3-4ded-89e2-f6898fcb8013"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=thegameoil}}
24.11 12:08:39 [Server] Server thread/ERROR [ElecCore]: A player disconnected from the server without connecting first!
24.11 12:08:39 [Disconnect] User thegameoil has disconnected, reason: Disconnected

(need help to fix this error)

**Comment by Elec332** [comment]
I will make the log error shorter

**Comment by SnowMntGaming** [comment]
What does this mean, I have a member of my server that can not join. This is the error I keep getting. Can I get any info on how to fix this?
