### ISSUE TITLE
Server Crash java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Orcinuss** [Elecs-Mods/ElecCore#71]
Server crashes when some players join the server. 
Crash report says elec332.core so I assume that is this. It seems to happen to certain people that have Deep Resonance set ups which I know uses this.

Minecraft 1.10.2
Direwolf20 1.10.2 v1.1.1
Forge: 12.18.2.2171
ElecCore 1.6.345

http://pastebin.com/Eu1R7xve

**Comment by Elec332** [comment]
Please tell me if you can reproduce this without sponge, bc I think that this is on sponge' s end

**Comment by Orcinuss** [comment]
How would I even test for this? I don't even know what is happening. I run a sponge server. This error crashes the server every 30 minutes to 4 hours. Any Ideas how I could even attempt to reproduce this without sponge.

@Elec332 Its odd that you think this might have to do with sponge. Most sponge related errors/crashes have a specific sponge class listed in the error. This one does not.

**Comment by Orcinuss** [comment]
Just found this:
https://github.com/SpongePowered/SpongeForge/issues/992

Will make a report on FTB forums for them to update the pack.

**Comment by Elec332** [comment]
Yep, this issue was not on my end.

**Comment by Orcinuss** [comment]
@Elec332 This is still happening on the latest SpongeForge. Are you sure it was not on your end?
This post "This issue was fixed by dev. Upload to latest ElecCore builds. Also make sure you are running LATEST SF builds" said by @bloodmc I think meant that you had already fixed this issue rather than they had. Although i'm still getting this bug.
