### ISSUE TITLE
crafting table 4 and elecCore

### ISSUE THREAD

**Issue by Blaedyn** [Elecs-Mods/ElecCore#72]
I installed the latest eleccore version but my crafting table 4 mod says that it needs to be the one before or later, since i have the later one i dont uderstand why i am having this issue, :/

**Comment by Elec332** [comment]
You are using an outdated version of CraftingTable IV, please update

**Comment by Blaedyn** [comment]
sorry i only just saw this email, i noticed i also got one that said my issue was closed, i will resubmit it with logs and screenshots when i try and launch it  again later today,


Blaedyn
________________________________

**Comment by Elec332** [comment]
You are using an outdated version of CraftingTable IV, please update
