### ISSUE TITLE
Elec Core crash when player logs in near world border

### ISSUE THREAD

**Issue by AussieWarGod** [Elecs-Mods/ElecCore#73]
This issue occurs when a player logs in within a few hundred blocks of the world border, our current workaround is a plugin that forces players to spawn on logout but it is a huge inconvenience. (for those who are also having this issue and are reading)

Only reproducible with sponge but i was hoping for an easy fix on your end, i am also pushing this issue to sponge in case it isn't fixable on your end, hopefully you can work together to find out which end it would be easiest to fix on.

I understand this issue may have been opened elsewhere but i couldn't find anywhere that the issue was actually pinpointed, that being the logging in near world border.

thanks for your time.

Crash log: http://mc.devcoftb.net/crashes/HP/crash-2016-12-04_17.14.05-server.txt
Server Log:  [fml-server-3.txt](https://github.com/Elecs-Mods/ElecCore/files/629889/fml-server-3.txt)

**Comment by AussieWarGod** [comment]
i just read this:
https://github.com/SpongePowered/SpongeForge/issues/992

which was closed only 2 days ago. if that is the same issue please disregard and my apologies.

**Comment by Elec332** [comment]
Its the same issue, and this crash was indeed not caused by ElecCore
