### ISSUE TITLE
Server crash - elec332.core.grid.AbstractGridHandler.checkChunkLoad

### ISSUE THREAD

**Issue by ProsperCraft** [Elecs-Mods/ElecCore#74]
I thought it was fixed because we had not had it on InfinityLite but it just turns out players were avoiding using the mod.  This crash we had prior was on Allthemods and Hermitpack.

Here it is again - 
https://gist.github.com/ProsperCraft/b6fe730b0e6c39c110ef45071ce29e09

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-323db46
    SpongeForge: 1.10.2-2171-5.1.0-BETA-1976
    Minecraft Forge: 12.18.2.2171

ElecCore-1.10.2-1.6.345.jar
deepresonance-1.10-1.3.1.jar

**Comment by ghost** [comment]
Player is also having the same issue only fix I have found is delete all the user nbt data...any help on this issue would be greatly appreciated.
http://pastebin.com/KTeYC0v1

**Comment by Elec332** [comment]
As I sateted a few times, this is a Sponge issue, and it has been fixed in the latest Sponge build.
https://github.com/SpongePowered/SpongeForge/issues/992
