### ISSUE TITLE
1.11.2 crash on loading with forestry installed 

### ISSUE THREAD

**Issue by 5kedone** [Elecs-Mods/ElecCore#77]
As above here is paste bin 

http://pastebin.com/PDjUEJSu

**Comment by Myknakryu** [comment]
Forge version: 1.11.2 2201
ElecCore version: 1.11-1.6.358
Forestry version: 1.11.2-5.3.0.3

Also crashes.
Game starts normally when ElecCore is removed.

Logs:
http://pastebin.com/JNJnZVCP

**Comment by Elec332** [comment]
Fixed in latest commit, https://github.com/Elecs-Mods/ElecCore/commit/a27bf8c9d59d422a9def70d9e5a5bb8f5b8cb31f

**Comment by 5kedone** [comment]
whens that a release ? would like to get back to testing and playing lol
