### ISSUE TITLE
Crash when loading ElecCore/Forestry 1.11

### ISSUE THREAD

**Issue by ChrisIds** [Elecs-Mods/ElecCore#78]
So.. Hey!
I started making my own 1.11 modpack, all goes well.. but then.. BOOOM.. crash.. (kek)
Well.. what happens is that ElecCore 1.11-1.6.358 (Newest) crashes with Forestry 1.11.2-5.3.0.8
[http://pastebin.com/nTTHBWdq](url)
(Didn't know of the upload option until after the pastebin mess^ gosh.)
[crash-2017-01-03_19.08.37-client.txt](https://github.com/Elecs-Mods/ElecCore/files/682979/crash-2017-01-03_19.08.37-client.txt)

In between errors I updated Forestry, but it still crashes. (Same thing, but with uploaded Forestry (5.3.0.9)).
[crash-2017-01-03_19.38.38-client.txt](https://github.com/Elecs-Mods/ElecCore/files/682976/crash-2017-01-03_19.38.38-client.txt)

Please help. Thanks. Appreciate it!

- Chris

@Elec332  (kek)

**Comment by 5kedone** [comment]
YEAH  i reported this awhile ago too was told it was fixed in latest comment but still no update to mod so either dont use deep resonance (only 1.11.2 mod that needs it at mo i think) or dont use forestry thems the choices till this api gets a update at last  lo

**Comment by ChrisIds** [comment]
Yup, I noticed.. That's why I added the issue, in case he forgot! lol
But i really only have Forester and DeepResonance that use RelecCore atm, so I can manage.

I see he added the fix for the problem in your post, but i dont know much about java coding and stuff, so i dont want to start with fixing it myself! lol
