### ISSUE TITLE
ClassNotFound issue,

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [Elecs-Mods/ElecCore#79]
http://pastebin.com/i2tmk8Jy

Elec Core: 1.6.360
Deep Resonance: 1.4.2
Forge 2815

**Comment by EPIICTHUNDERCAT** [comment]
just tested with 1.6.365, same issue

**Comment by Elec332** [comment]
![image](https://cloud.githubusercontent.com/assets/6115944/21688585/b964a432-d36d-11e6-9298-8cf35f4f9182.png)
Dafuq....

**Comment by EPIICTHUNDERCAT** [comment]
Did you refractor things? I know that messes things up? I had issues like that.
