### ISSUE TITLE
[Crash] Loading existing world

### ISSUE THREAD

**Issue by robaimes** [Elecs-Mods/ElecCore#8]
Reported to me by someone else, (so this is a rough translation) but the basic details are:
- Created new world
- Play for a bit
- Close game
- Open the same world
- Crashes

Here is the attached report: http://pastebin.com/qFM9cwrk

**Comment by robaimes** [comment]
As an update, this appears to be an isolated instance of the issue. Reinstalling his instance of MC appears to have fixed the issue.

**Comment by Elec332** [comment]
Good to hear :)

**Comment by robaimes** [comment]
Seem to have another instance of this issue. It's strange, and was caused due to a power cut while playing the world.

http://pastebin.com/kVTRtCKw

**Comment by Elec332** [comment]
Yes, this will have caused data corruption, nothing I can do about that.
To fix the error, he should go to the save folder -> folder named "elec332" and clear all contents inside.

This will fix this :)

**Comment by robaimes** [comment]
Alright, cheers. I'll note it down and inform them!

**Comment by ghost** [comment]
I have the same issue, i got a power cut and now every time i try to get into my world it crashes... I've tried cleaning the "elec332" folder, but that didnt work, also i noticed that the .dat files on the folder were empty.
I'm using Space Astronomy Modpack by mjrlegends.

(Crash Report)

[crash-2017-03-08_21.03.56-server.txt](https://github.com/Elecs-Mods/ElecCore/files/829331/crash-2017-03-08_21.03.56-server.txt)
