### ISSUE TITLE
Crash On Right Click

### ISSUE THREAD

**Issue by HNGamingUK** [Elecs-Mods/ElecCore#81]
Hello, my client crashes whenever I right click anything and it seems to be ElecCore to be the cause.

Here is the crash log: 

http://pastebin.com/s37LNp8g

**Comment by mrgreaper** [comment]
im getting the same crash,
right clicked a door and a crate boom
wierdly my test server is fine, i dont crash on that

**Comment by Morpheus1101** [comment]
I to am getting this error, log @ https://puu.sh/tcKWa/4c3b8c78b6.txt

**Comment by Elec332** [comment]
Fixed in latest release
