### ISSUE TITLE
Crash when Opening Chest

### ISSUE THREAD

**Issue by Medusalem** [Elecs-Mods/ElecCore#82]
Hey,

Game is crashing opening chest, vanilla and modded chests are crashing the game equaly!
If there is anything on Information that i could give you, yust Ask!

Minecraft  1.10.2
Forge        12.18.3.2185
Eleccore    ElecCore-1.10.2-1.6.379
Crashlog:   http://pastebin.com/VxX8HvGR

Greetings :)

**Comment by Elec332** [comment]
Im sorry, but you are using 1.6.178:     
-UCHIJAAAA   eleccore{1.6.378} [ElecCore] (ElecCore-1.10.2-1.6.378.jar)

Please update to 1.6.179, which fixes this issue ;)
