### ISSUE TITLE
Right click broken for tools (ElecCore-1.10.2-1.6.379.jar)

### ISSUE THREAD

**Issue by Thiana** [Elecs-Mods/ElecCore#83]
The right click actions of vanilla and tinker tools are not working with the latest ElecCore. Blocks can be placed normally and inventories are usable. Thanks.

**Comment by Elec332** [comment]
-Can you give me a specific example?
-Are you 100% sure ElecCore is the cause?

**Comment by Thiana** [comment]
Apparently it's a problem with another mod I'd forgotten I installed (https://minecraft.curseforge.com/projects/improved-hoes). I made the assumption it was ElecCore because of the recent r-click issues. Sorry.
