### ISSUE TITLE
Crash on startup of Server

### ISSUE THREAD

**Issue by Gamerbolts** [Elecs-Mods/ElecCore#84]
Hello. I am creating a modpack and trying to load the server, it gets to generator world. Then crashes with this error http://pastebin.com/6cjkZmup Not sure what it means but saw Elec332 on there. Any ideas?

**Comment by leytilera** [comment]
i have the same problem

**Comment by Elec332** [comment]
Please try the latest version (build 407), and open a new ticket is the issue persists
