### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by alicheek** [Elecs-Mods/ElecCore#86]
Modpack: dw20 1.10.2 1.3.2
ElecCore: ElecCore-1.10.2-1.6.345.jar
SpongeForge: 1.10.2-2202-5.1.0-BETA-2034

Crash report: http://pastebin.com/4F5NZAPr

We have had quite a few of these crashes now not too sure whats causing it.

**Comment by ghost** [comment]
we have had the same... but only effecting users that have placed dimensional Transceivers 
To make the crash worse its not been every log in but every other, and they crash the server on the second log in..... taken two weeks to find the common thread among my now two crashies 

Im not 100% sure its the dimensional Transceivers but im 70% (its such a hard crash to diagnose)

**Comment by Elec332** [comment]
Upfdate to latest SpongForge
