### ISSUE TITLE
Error on World Creation - NoClassDefFoundError: elec332/core/module/ModuleManager$$Lambda$33

### ISSUE THREAD

**Issue by WittyWhiscash** [Elecs-Mods/ElecCore#89]
This occurs when I attempted to create a world with your mod in this modpack.
Once I had started generating the world, Minecraft hung and checking the log I found this: http://pastebin.com/icQWyGxe

It was a one-off occurrence, but I would hope that it might be reproduceable.

Minecraft Version: 1.10.2
Forge Version: 1.10.2-12.18.3.2185
Mod Version: ElecCore-1.10.2-1.6.379.jar

**Comment by Elec332** [comment]
Probably fixed in latest release, please create a new issue if it persists
