### ISSUE TITLE
[1.11-1.7.400] Crash on startup

### ISSUE THREAD

**Issue by Aphyxia** [Elecs-Mods/ElecCore#92]
http://pastebin.com/24txLEuN

Reverting to previous version 1.11-1.6.381 fixed this.

**Comment by kreezxil** [comment]
Notes:
     appears to be looking for a client side class during server startup
     internally you have designated as 1.7.9999.custom

crash report:
https://gist.github.com/9c6bd2fd6c02427047324ec483a77a93

fml server latest:
https://gist.github.com/1f51cd66987b797d9bd3eb484212f710

Same thing happened on a client startup.

client crash report: https://gist.github.com/kreezxil/37f4b8ae919b21960cfa63ae2e421c3f

**Comment by Aphyxia** [comment]
My problem was fixed in 1.11-1.7.402.
